// src/components/TimePicker.vue
<template>
  <div>
    <select v-model="hour">
      <option
        v-for="option in availableHours"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
    <select v-model="minute">
      <option
        v-for="option in availableMinutes"
        :key="option.value"
        :value="option.value"
      >
        {{ option.label }}
      </option>
    </select>
  </div>
</template>

<script>
export default {
  props: {
    date: {
      type: Date,
      required: true
    }
  },
  computed: {
    hour: {
      get() {
        return this.date.getHours();
      },
      set(hh) {
        const date = new Date(this.date);
        date.setHours(hh);
        this.$emit('update:date', date);
      }
    },
    minute: {
      get() {
        return this.date.getMinutes();
      },
      set(mm) {
        const date = new Date(this.date);
        date.setMinutes(mm);
        this.$emit('update:date', date);
      }
    },
    availableHours() {
      const hours = [];
      for (let h = 0; h < 24; h++) {
        hours.push({
          label: h,
          value: h
        });
      }
      return hours;
    },
    availableMinutes() {
      const minutes = [];
      for (let m = 0; m < 60; m++) {
        let minute = m.toString();
        if (minute.length < 2) {
          minute = '0' + minute;
        }
        minutes.push({
          label: minute,
          value: m
        });
      }
      return minutes;
    }
  }
};
</script>

// packages/react-date-range-picker/src/components/TimePicker.js
import React from 'react';
import PropTypes from 'prop-types';

function Hours(props) {
  const { onChange, ...others } = props;
  const hours = [];
  for (let h = 0; h < 24; h++) {
    hours.push(<option key={h} value={h}>{h}</option>);
  }

  const onChangeHours = e => {
    onChange(parseInt(e.target.value));
  }

  return <select {...others} onChange={onChangeHours}>{hours}</select>;
}

function Minutes(props) {
  const { onChange, ...others } = props;
  const minutes = [];
  for (let m = 0; m < 60; m += props.increment) {
    const minute = m < 10 ? '0' + m : m.toString();
    minutes.push(<option key={m} value={m}>{minute}</option>);
  }

  const onChangeMinutes = e => {
    onChange(parseInt(e.target.value));
  }

  return <select {...others} onChange={onChangeMinutes}>{minutes}</select>;
}

export default function TimePicker(props) {
  const { onChange, value, minuteIncrement, ...others } = props;

  const onChangeHours = hours => {
    const d = new Date(value);
    d.setHours(hours);
    onChange(d);
  }

  const onChangeMinutes = minutes => {
    const d = new Date(value);
    d.setMinutes(minutes);
    onChange(d);
  }

  return (
    <div {...others}>
      <Hours
        value={value.getHours()}
        onChange={onChangeHours}
      />
      <Minutes
        value={value.getMinutes()}
        onChange={onChangeMinutes}
        increment={minuteIncrement}
      />
    </div>
  );
}

TimePicker.propTypes = {
  minuteIncrement: PropTypes.number,
  value: PropTypes.instanceOf(Date),
  onChange: PropTypes.func
};
